name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      LOGFIRE_SEND_TO_LOGFIRE: 'false'
      TESTING: 'true'

    steps:
    - uses: actions/checkout@v4

    - name: set up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Set up environment variables
      run: |
          echo "G_PRIVATE_KEY=${{ secrets.G_PRIVATE_KEY }}" >> $GITHUB_ENV
          echo "G_PRIVATE_KEY_ID=${{ secrets.G_PRIVATE_KEY_ID }}" >> $GITHUB_ENV
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> $GITHUB_ENV
          echo "MASTER_TOKEN=${{ secrets.MASTER_TOKEN }}" >> $GITHUB_ENV
          echo "HEROKU_API_KEY=${{ secrets.HEROKU_API_KEY }}" >> $GITHUB_ENV

    - name: install dependencies
      run: |
          make install
          pip freeze

    - name: test
      run: make test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    needs:
      - test
    if: "github.ref == 'refs/heads/main' && success()"
    runs-on: ubuntu-latest

    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP: tw-plutus

    steps:
      - uses: actions/checkout@v4
      - run: git fetch --unshallow
      - run: git switch main
      - run: git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git
      - run: git push heroku main